# For MSA -인식 문의
spring:
 application:
   name: server-quiz
 config:
   import: optional:configserver:http://config:8888
 cloud:
   openfeign:
     client:
       config:
         default:
           connectTimeout: 100000
           readTimeout: 100000
           loggerLevel: basic
