spring:
  profiles:
    active: local
    include: oauth, app, db

server:
  error:
    include-stacktrace: never
  error.whitelabel.enabled: true

spring.mvc.static-path-pattern: /static/**
springdoc.swagger-ui.path: /swagger-ui.html


logging:
  level:
    org.springframework.security : DEBUG
    org.springframework.jdbc.core : DEBUG

# application.yml


