spring:
  application:
    name: server-gateway

  cloud:
    gateway:
      routes:
        - id: server-member
          uri: lb://server-member
          predicates:
            - Path=/api/member/**




#        - id: server_member
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/member/**
#
#        - id: server_gpt
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/gpt/**
#
#        - id: server_editor
#          uri: http://localhost:8085
#          predicates:
#            - Path=/api/editor/**
#
#        - id: server_search
#          uri: http://localhost:8086
#          predicates:
#            - Path=/api/search/**
#
#        - id: server_diagram
#          uri: http://localhost:8087
#          predicates:
#            - Path=/api/diagram/**
#
#        - id: server_quiz
#          uri: http://localhost:8088
#          predicates:
#            - Path=/api/quiz/**

server:
  port: 8080

eureka:
  instance:
    instance-id: gateway-service-${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka