# For MSA -인식 문의
spring:
   application:
     name: server-editor
   config:
     import: optional:configserver:http://config:8888
   data:
      redis:
        host: www.hype-note.com
        port: 6379
        password: "!esser101Panda"

# spring:
#   data:
#     mongodb:
#       uri: mongodb://localhost:27017/Editor